export const ADD_PERSON = 'ADD_PERSON',
    SET_PERSONS = 'SET_PERSONS',
    SET_LOADING = 'SET_LOADING',
    SET_LOADING_QUOTE = 'SET_LOADING_QUOTE',
    SET_PERSON_BY_ID = 'SET_PERSON_BY_ID',
    IS_GRID = 'IS_GRID',
    GET_QUOTE_BY_ID = 'GET_QUOTE_BY_ID';