export const ADD_PERSON = 'ADD_PERSON',
    SET_PERSONS = 'SET_PERSONS',
    SET_LOADING = 'SET_LOADING',
    SET_LOADING_QUOTE = 'SET_LOADING_QUOTE',
    SET_PERSON_BY_ID = 'SET_PERSON_BY_ID',
    SET_QUOTE_BY_ID = 'SET_QUOTE_BY_ID';